package modelo;
// Generated 05-abr-2020 6:09:23 by Hibernate Tools 4.3.1

/**
 * Alquiler generated by hbm2java
 */
 public class Alquiler implements java.io.Serializable {

    private Integer id;
    private Automobil automobil;
    private Cliente cliente;
    private String fechaInicio;
    private String fechaFin;
    private String observaciones;
    /**
     * *******************************************************
     */
    //estas variables son auxiliares, solo sirven para rellenar la tabla de resgistro
    //porque el tableView solo puede leer atributos de un objeto
    private String nombreMarca;
    private String nombreCliente;
    private int dni; 
    private int id_coche;

    public Alquiler() {
    }

    public Alquiler(Automobil automobil, Cliente cliente) {
        this.automobil = automobil;
        this.cliente = cliente;
        nombreMarca = "";
        nombreCliente = "";
        dni=0;
        id_coche=0;
    }

    public Alquiler(Automobil automobil, Cliente cliente, String fechaInicio, String fechaFin, String observaciones) {
        this.automobil = automobil;
        this.cliente = cliente;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.observaciones = observaciones;
        nombreMarca = "";
        nombreCliente = "";
        dni =0;
        id_coche=0;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Automobil getAutomobil() {
        return this.automobil;
    }

    public void setAutomobil(Automobil automobil) {
        this.automobil = automobil;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public String getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public String getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public String getNombreMarca() {
        return nombreMarca;
    }

    public void setNombreMarca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }

    public String getNombreCliente() {
        return nombreCliente;
    }

    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }

    public int getDni() {
        return dni;
    }

    public void setDni(int dni) {
        this.dni = dni;
    }

    public int getId_coche() {
        return id_coche;
    }

    public void setId_coche(int id_coche) {
        this.id_coche = id_coche;
    }

}
