package modelo;
// Generated 05-abr-2020 6:09:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Automobil generated by hbm2java
 */
public class Automobil implements java.io.Serializable {

    private Integer id;
    private String marca;
    private String modelo;
    private String matricula;
    private Integer numRuedas;
    private Integer autonomia;
    private String color;
    private Integer km;
    private char combustible;
    private Integer plazas;
    private String tipo;
    private Boolean enUso;
    private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);
    //aqui van los atributos auxiliares que uso para hacer los tableView mas descriptivos
    private String combustibleString;
    public Automobil() {
    }

//constructor auxiliar	
    public Automobil(String matricula, char combustible) {
        this.matricula = matricula;
        this.combustible = combustible;
    }

    public Automobil(String marca, String modelo, String matricula, Integer numRuedas, Integer autonomia, String color, Integer km, char combustible, Integer plazas, String tipo, Boolean enUso, Set<Alquiler> alquilers) {
        this.marca = marca;
        this.modelo = modelo;
        this.matricula = matricula;
        this.numRuedas = numRuedas;
        this.autonomia = autonomia;
        this.color = color;
        this.km = km;
        this.combustible = combustible;
        this.plazas = plazas;
        this.tipo = tipo;
        this.enUso = enUso;
        this.alquilers = alquilers;

    }

    public Automobil(String marca, String modelo, String matricula, Integer numRuedas, Integer autonomia, String color, Integer km, char combustible, Integer plazas, String tipo, Boolean enUso) {
        this.marca = marca;
        this.modelo = modelo;
        this.matricula = matricula;
        this.numRuedas = numRuedas;
        this.autonomia = autonomia;
        this.color = color;
        this.km = km;
        this.combustible = combustible;
        this.plazas = plazas;
        this.tipo = tipo;
        this.enUso = enUso;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getMarca() {
        return this.marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getModelo() {
        return this.modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getMatricula() {
        return this.matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    public Integer getNumRuedas() {
        return this.numRuedas;
    }

    public void setNumRuedas(Integer numRuedas) {
        this.numRuedas = numRuedas;
    }

    public Integer getAutonomia() {
        return this.autonomia;
    }

    public void setAutonomia(Integer autonomia) {
        this.autonomia = autonomia;
    }

    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Integer getKm() {
        return this.km;
    }

    public void setKm(Integer km) {
        this.km = km;
    }

    public char getCombustible() {
        return this.combustible;
    }

    public void setCombustible(char combustible) {
        this.combustible = combustible;
    }

    public Integer getPlazas() {
        return this.plazas;
    }

    public void setPlazas(Integer plazas) {
        this.plazas = plazas;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public Boolean getEnUso() {
        return this.enUso;
    }

    public void setEnUso(Boolean enUso) {
        this.enUso = enUso;
    }

    public Set<Alquiler> getAlquilers() {
        return this.alquilers;
    }

    public void setAlquilers(Set<Alquiler> alquilers) {
        this.alquilers = alquilers;
    }

    public String getCombustibleString() {
        return combustibleString;
    }

    public void setCombustibleString(String combustibleString) {
        this.combustibleString = combustibleString;
    }

    @Override
    public String toString() {
        return "Automobil{" + "id=" + id + ", marca=" + marca + ", modelo=" + modelo + ", matricula=" + matricula + ", numRuedas=" + numRuedas + ", autonomia=" + autonomia + ", color=" + color + ", km=" + km + ", combustible=" + combustible + ", plazas=" + plazas + ", tipo=" + tipo + ", enUso=" + enUso + ", alquilers=" + alquilers + '}';
    }

}
