package modelo;
// Generated 05-abr-2020 6:09:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private int dni;
     private String nombre;
     private Integer telefono;
     private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);
     private int contador;

    public int getContador() {
        return contador;
    }

    public void setContador(int contador) {
        this.contador = contador;
    }

    public Cliente() {
    }

    public Cliente(int dni, String nombre, Integer telefono) {
        this.dni = dni;
        this.nombre = nombre;
        this.telefono = telefono;
    }

	
    public Cliente(int dni) {
        this.dni = dni;
    }
    public Cliente(int dni, String nombre, Integer telefono, Set<Alquiler> alquilers) {
       this.dni = dni;
       this.nombre = nombre;
       this.telefono = telefono;
       this.alquilers = alquilers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Set<Alquiler> getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set<Alquiler> alquilers) {
        this.alquilers = alquilers;
    }




}


